name: 'Update latest Docker tag'
description: >
  Update the latest tag of a Docker repo, but only if the new image is a (semver) newer version than what's there already.
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  repository:
    description: 'Docker image repository to check and update. To update multiple repos, pass a multiline string.'
    required: true
  candidate-tag:
    description: 'The newly-pushed image tag that possibly should be promoted to latest'
    required: true
  latest-tag:
    description: 'The image tag to check and possibly update'
    required: true
    default: 'latest'
  version-source:
    description: "Read an image's version from a label (label:...) or environment variable (env:...)"
    required: true
    default: 'label:org.opencontainers.image.version'
  promote-prerelease:
    description: 'Allow prerelease versions to replace non-prerelease latest'
    default: 'false'
  coerce-semver:
    description: 'Coerce detected version values to semver'
    default: 'false'
  manifest-platform:
    description: 'Read the current version from the container config of this platform in a multi-arch index / manifest list'
    default: 'linux/amd64'
outputs:
  updated:
    description: Whether or not the image was updated (true or false)
  latest-version:
    description: The detected version of the latest tag
  candidate-version:
    description: The detected version of the candidate tag
runs:
  using: 'node20'
  main: 'dist/index.js'
